language: elixir
elixir:
  - 1.7
otp_release:
  - 21.0

branches:
  only:
  - master

dist: trusty
sudo: false

install:
  - mix local.rebar --force
  - mix local.hex --force
script: ./script/cibuild
